FROM ruby

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nodejs && \
    gem install rails

WORKDIR /opt/app
ONBUILD COPY app/. .
ONBUILD RUN bundle install && \
            rake db:migrate && \
            rake db:seed
