FROM ruby

RUN apt-get update && \
    apt-get install -y nodejs build-essential libpq-dev sqlite3 && \
    gem install rails


ONBUILD WORKDIR /opt/app
ONBUILD COPY app/. .
ONBUILD RUN bundle install && \
            bundle exec rake db:migrate && \
            bundle exec rake db:seed
